import test from 'node:test'; import assert from 'node:assert/strict'; import { mock } from 'node:test'; import { MemoryStudioClient } from '../src/memory-studio-client.ts'; import { hashSha256_16 } from '../src/hash.ts';
const request = { prompt: 'hi', context: null, fingerprint: { projectPath: '/x', agentId: 'claude-code', sessionId: 'h', gitBranch: 'main' }, activeCatalog: [], schemaVersion: 3 };
const response = { systemMessage: 'ok', matchedSkills: [], matchedRules: [], matchedPersonas: [], pruningDecisions: { rejectedByFloor: [], rejectedByBudget: [], rejectedByAttentionTier: [], rejectedByNegativeFeedback: [], rejectedByCriticalDropped: [] }, latencyMs: { embedding: 0, retrieval: 0, rerank: 0, total: 0 }, decisionTraceId: 'd', warnings: [], schemaVersion: 3 };
function setFetch(value) { mock.method(globalThis, 'fetch', value); }
test('posts request with hashed tenant and prompt-only null context', async (t) => { let seen; setFetch(async (url, options) => { seen = { url, options }; return { ok: true, json: async () => response }; }); const result = await new MemoryStudioClient({ baseURL: 'http://example.test/', tenantId: 'tenant-abc' }).augment(request); assert.equal(seen.url, 'http://example.test/augment'); assert.equal(seen.options.method, 'POST'); assert.equal(seen.options.headers['Content-Type'], 'application/json'); const body = JSON.parse(seen.options.body); assert.equal(body.context, null); assert.equal(body.tenantId, hashSha256_16('tenant-abc')); assert.notEqual(body.tenantId, 'tenant-abc'); assert.deepEqual(result, response); t.mock.restoreAll(); });
test('returns valid response with empty matches', async (t) => { setFetch(async () => ({ ok: true, json: async () => ({ ...response, emptyReason: 'no_active_items' }) })); const result = await new MemoryStudioClient({ baseUrl: 'http://x', tenantId: 't' }).augment(request); assert.deepEqual(result.matchedSkills, []); assert.equal(result.emptyReason, 'no_active_items'); t.mock.restoreAll(); });
test('throws SdkError for 4xx and 5xx', async (t) => { for (const status of [400, 500]) { setFetch(async () => ({ ok: false, status, text: async () => 'bad' })); await assert.rejects(() => new MemoryStudioClient({ baseUrl: 'http://x', tenantId: 't' }).augment(request), error => error.code === 'http_error' && error.message.includes(String(status))); t.mock.restoreAll(); } });
test('throws SdkError for malformed JSON', async (t) => { setFetch(async () => ({ ok: true, json: async () => { throw new Error('bad json'); } })); await assert.rejects(() => new MemoryStudioClient({ baseUrl: 'http://x', tenantId: 't' }).augment(request), error => error.code === 'invalid_response'); t.mock.restoreAll(); });
test('does not synthesize cacheHit', async (t) => { setFetch(async () => ({ ok: true, json: async () => response })); const result = await new MemoryStudioClient({ baseUrl: 'http://x', tenantId: 't' }).augment(request); assert.equal(Object.hasOwn(result, 'cacheHit'), false); t.mock.restoreAll(); });
